apiVersion: apps/v1
kind: Deployment
metadata:
  name: and-so-on
  labels:
    app: and-so-on
spec:
  replicas: 1
  selector:
    matchLabels:
      app: and-so-on
  template:
    metadata:
      labels:
        app: and-so-on
    spec:
      containers:
      - name: and-so-on
        image: 192.168.150.161/library/and-so-on:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: and-so-on-service
spec:
  selector:
    app: and-so-on
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
